#!/bin/sh

DEFAULT_NTP="time.cloudflare.com"
CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

# move aside original config file
mv -f /etc/chrony/chrony.conf /etc/chrony/chrony.conf.bak

# update permissions on /var/lib/chrony directory
chown -R chrony:chrony /var/lib/chrony

# remove previous pid file if it exist
rm -f /var/run/chrony/chronyd.pid

## dynamically populate chrony config file.
{
  echo "# https://github.com/cturra/docker-ntp"
  echo
  echo "# chrony.conf file generated by startup script"
  echo "# located at /opt/startup.sh"
  echo "server 127.127.1.0"
  echo "local stratum 10"
  echo "driftfile /var/lib/chrony/chrony.drift"
  echo "makestep 0.1 3"
  echo "rtcsync"
  echo
  echo "allow all"
} >> ${CHRONY_CONF_FILE}

## startup chronyd in the foreground
/usr/sbin/chronyd -d -s
